### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by ArmorDarks** [dmitriiabramov/react-prop-types-check#2]
Hi!

Thanks for making this lib.

Just wanted to know, is it maintained? Is it usable in real projects, or it's just an experiment?

**Comment by boujeepossum** [comment]
@ArmorDarks hey! it was just an experiment :)
i would highly recommend using https://flowtype.org/ instead
and https://codemix.github.io/flow-runtime/#/ if you need runtime checks!

**Comment by ArmorDarks** [comment]
Hi @dmitriiabramov 

Thanks for quick reply :)

We're locked with CoffeeScript for now, which doesn't play nice with Flow, so I'm exploring possible runtime solutions. `flow-runtime` seems like an interesting one, so we'll check it out too. Thanks for suggestion!
